# Generated by Django 4.2.4 on 2023-08-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planets_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planet",
            name="climates",
            field=models.ManyToManyField(
                blank=True, null=True, to="planets_api.climate"
            ),
        ),
        migrations.AlterField(
            model_name="planet",
            name="population",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="planet",
            name="terrains",
            field=models.ManyToManyField(
                blank=True, null=True, to="planets_api.terrain"
            ),
        ),
    ]
