# Generated by Django 4.2.4 on 2023-08-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planets_api", "0002_alter_planet_climates_alter_planet_population_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planet",
            name="climates",
            field=models.ManyToManyField(blank=True, to="planets_api.climate"),
        ),
        migrations.AlterField(
            model_name="planet",
            name="terrains",
            field=models.ManyToManyField(blank=True, to="planets_api.terrain"),
        ),
    ]
